# A model to deploy a web project based on github actions
# The name of the whole workflow
name: Build and Deploy Web

# Differents triggers and branches
on:
  push:
    branches:
      - main
      - develop
      - staging
      - dev
  pull_request:
    branches:
      - main
      - develop
      - staging
      - dev

# define jobs or process
jobs:
  caching-and-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build     
  deploy:
    name: Deploy
    needs: caching-and-build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      # deploiement pour la branche main
      - name: Depoy to Firebase on Main Branch
        if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'deploiement')
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # deploiement pour la branche develop
      - name: Depoy to Firebase on Develop Branch
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/dev') && contains(github.event.head_commit.message, 'deploiement')
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # deploiement pour la branche staging
      - name: Depoy to Firebase on staging Branch
        if: github.ref == 'refs/heads/staging' && contains(github.event.head_commit.message, 'deploiement')
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:${{ env.TAG_NAME }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
