name: Project-Info-Actions
on:
  push:
    branches:
      - dev
      - staging
      - prod
  pull_request:
    branches:
      - dev
      - staging
      - prod
  workflow_call:
    inputs:
      username: 
        required: true
        type: string
    secrets:
      ORGANISATION_TOKEN:
        token: ${{ secrets.PERSONNAL_ACCESS_TOKEN }}
jobs:
  user-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The Jobs were writen by ${{ github.actor }}."
      - run: echo "The status of the jobs is ${{ job.status }}."
