name: Project-Info-Actions
on:
  push:
    branches:
      - main
      - dev
      - stagge
      - prod
  pull_resquest:
    branches:
      - main
      - dev
      - stagge
      - prod
jobs:
  user-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The Jobs were writen by ${{ github.actor }}."
      - run: echo "The status of the jobs is ${{ job.status }}."